/**
 * Use this bad boy to keep this sorted: https://github.com/Tyriar/vscode-sort-lines
 */

const Commands = {
    A: 'a',
    ADD: 'add',
    ANNOUNCE: 'announce',
    ANNOUNCEMENTS: 'announcements',
    BUG: 'bug',
    BUMP: 'bump',
    CHANNEL: 'channel',
    CRASH: 'crash',
    CREATE: 'create',
    DATA: 'data',
    DELETE: 'delete',
    DELETE_ALL: 'delete-all',
    DESCRIBE: 'describe',
    DETAILS: 'details',
    DUMP: 'dump',
    EMPTY: 'empty',
    EMPTY_ALL: 'empty-all',
    GLOBAL: 'global',
    GET: 'get',
    GENERATE: 'generate',
    H: 'h',
    HELP: 'help',
    KEYWORD: 'keyword',
    KW: 'kw',
    INVITE: 'invite',
    PATCHNOTES: 'patchnotes',
    PERMISSIONS: 'permissions',
    PING: 'ping',
    ROLE: '-role', // reserved
    REPORT: 'report',
    RESET: 'reset',
    RM: 'rm',
    RMALL: 'rmall',
    SET: 'set',
    SHOW: 'show',
    START: 'start',
    STOP: 'stop',
    SUGGEST: 'suggest',
    T: 't',
    TALLY_REACTIONS: 'tally-reactions',
    TEST: 'test',
    TIMER: 'timer',
    TIMERS: 'timers',
    TALLY_GROUP_ADD: 'tg-add',
    TALLY_GROUP_RM: 'tg-rm',
    TALLY_GROUP_GET: 'tg-get',
    TALLY_GROUP_EDIT: 'tg-edit',
    TALLY_GROUP_SHOW: 'tg-show',
    TALLY_GROUP_BUMP: 'tg-bump',
    TALLY_GROUP_DUMP: 'tg-dump',
    UPDATE: 'update',
    MIGRATE: 'migrate'
}

export default Commands;