/**
 * Use this bad boy to keep this sorted: https://github.com/Tyriar/vscode-sort-lines
 */

export default {
    A: 'a',
    ADD: 'add',
    ANNOUNCE: 'announce',
    ANNOUNCEMENTS: 'announcements',
    BUG: 'bug',
    BUMP: 'bump',
    CHANNEL: 'channel',
    CRASH: 'crash',
    CREATE: 'create',
    DELETE: 'delete',
    DELETE_ALL: 'delete-all',
    DESCRIBE: 'describe',
    DETAILS: 'details',
    DUMP: 'dump',
    EMPTY: 'empty',
    EMPTY_ALL: 'empty-all',
    GLOBAL: 'global',
    GET: 'get',
    GENERATE: 'generate',
    H: 'h',
    HELP: 'help',
    KEYWORD: 'keyword',
    KW: 'kw',
    INVITE: 'invite',
    PATCHNOTES: 'patchnotes',
    PERMISSIONS: 'permissions',
    ROLE: '-role', // reserved
    REPORT: 'report',
    RESET: 'reset',
    RM: 'rm',
    RMALL: 'rmall',
    SET: 'set',
    SHOW: 'show',
    START: 'start',
    STOP: 'stop',
    SUGGEST: 'suggest',
    T: 't',
    TEST: 'test',
    TIMER: 'timer',
    TIMERS: 'timers',
    UPDATE: 'update'
}