FROM arm32v7/node

COPY . /opt/tally-bot

# remove dev credentials
RUN rm -f .env

RUN cd /opt/tally-bot && yarn install

WORKDIR /opt/tally-bot

HEALTHCHECK --interval=5s --timeout=2s --retries=6 \
  CMD curl --silent --fail localhost:4200 || exit 1

ENTRYPOINT ["yarn", "start-prod"]